version: "2.13"
services:
  app:
    build:
      context:  .
    volumes:
      - .:/react
    ports:
      - 3000:3000
    image: app:react
    container_name: react_container
    command: npm run dev